apiVersion: v2
name: cors-proxy
description: A Helm chart for CORS proxy server
type: application
version: 1.2.0
appVersion: 1.2.0
home: https://github.com/hiteshnayak305/cors-proxy
icon: https://raw.githubusercontent.com/hiteshnayak305/cors-proxy/main/logo.png
sources:
  - https://github.com/hiteshnayak305/cors-proxy
maintainers:
  - name: hiteshnayak305
    email: hiteshnayak305@noreply.github.com
dependencies:
  - name: common
    repository: https://bjw-s-labs.github.io/helm-charts
    version: 4.4.0
annotations:
  artifacthub.io/category: security
  artifacthub.io/containsSecurityUpdates: "true"
  artifacthub.io/changes: |
    - kind: security
      description: upgrade base image to node 24 alpine lts
    - kind: changed
      description: upgraded common library to 4.3.0
